### ISSUE TITLE
Consistent Region Support for HDFS operators

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.hdfs#28]
Changes required to support consistent region

Wiki describing behavior for HDFS2FileSink... please provide feedback to this issue.
https://github.com/IBMStreams/streamsx.hdfs/wiki/Consistent-Region-Support-for-HDFS-operators

**Comment by chanskw** [comment]
Figured out how to get append to work.  Updated design using append.
Major changes:
* not adding new parameters to move files
* files will be opened in append mode in reset.  
* files will be opened in overwrite mode in all other scenarios. (maintaining current behavior)

**Comment by hildrum** [comment]
I think the output tuple corresponding to any files closed in the reset method could be lost if there are two resets (ie, reset, then reset again before a checkpoint) unless the tuple is sent out of the consistent region.   I didn't see this mentioned in the spldoc.

**Comment by chanskw** [comment]
Yes, I know... haven't finished doc update.

**Comment by chanskw** [comment]
Design updated with HDFS2FileSource and HDFS2DirectoryScan

**Comment by gabijs** [comment]
Comments for HDFS2DirectoryScan:

1) Is it possible for a file with an older timestamp to be visible to the DirectoryScan after a file with an older timestamp (i.e., on a later directory scan cycle)?

2) Add recommendation for the DirectoryScan to be fused with its downstream operator. This helps limiting the size of the queues on a periodic setting, and helps on timeout management in an operator-driven setting. On periodic, a new tuple will be placed on the channel only after been fully processed by the downstream operator. Drains and resets will be faster if the channels are not full. On operator-driven, makeConsistent() (which kicks the timeout) will be called only after the tuple has been fully processed by the downstream operator. This ends up being important to DirectoryScan because it is generally followed by FileSource, which can take a long time to process a single tuple. 

3) "Files with same timestamps" section -> "Modify the design a little bit" - I would remove this and describe only the design that works. In the descriptions above, the checkpoint content is already described as the timestamp and file name. It suffices to say that the operator orders files by timestamp and by name (within the same timestamp). I wonder though if this might have a similar problem as hypothesized in question 1). For example, is it possible that not all files with the same timestamp are visible at the same DirectoryScan "scan cycle"? If so, a problem could happen if the new file appears on a following scan cycle but its shows up before than a previously submitted file when in sorted order. 

4) Case 2 - I agree we do not have to do this initially. Is the operator multi-threaded even when it processes data from its input stream?

**Comment by chanskw** [comment]
(1)  I have never seen this.. and never even able to produce files with same timestamp.  In your testing of the directoryScan, have you seen this happen?  or have you seen this happening in any file system?

(2) ok

**Comment by gabijs** [comment]
1) Eric implemented DirectoryScan, so I can't say it. The issue is that we establish the consistent line by the timestamp and alphabetical order, which is why I asked if this is indeed a guarantee we can rely on. Given you had a section on the design for disambiguating on timestamps, I assumed it was possible at least to get files with the same timestamps. I tried creating two files in my NFS home (2 repetitions only), and I did not succeed to create both files with the same timestamp:

a:~> touch bla1 bla2
a:~> stat bla1
  File: bla1
  Size: 0               Blocks: 0          IO Block: 1048576 regular empty file
Device: 1ah/26d Inode: 62392734    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1709/gajacque)   Gid: ( 2015/ ccgroup)
Access: 2015-01-19 16:54:19.843200969 -0500
**Modify: 2015-01-19 16:54:19.843200969 -0500**
Change: 2015-01-19 16:54:19.843200969 -0500
a:~> stat bla2
  File: bla2
  Size: 0               Blocks: 0          IO Block: 1048576 regular empty file
Device: 1ah/26d Inode: 62392736    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1709/gajacque)   Gid: ( 2015/ ccgroup)
Access: 2015-01-19 16:54:19.844061284 -0500
**Modify: 2015-01-19 16:54:19.844061284 -0500**
Change: 2015-01-19 16:54:19.844061284 -0500 

I tried then on the /tmp directory, and succeeded on the first try: 

a:/tmp> touch bla1 bla2
a:/tmp> stat bla1 bla2 
  File: bla1
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: fd04h/64772d    Inode: 19          Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1709/gajacque)   Gid: ( 2015/ ccgroup)
Access: 2015-01-19 16:55:04.524869815 -0500
**Modify: 2015-01-19 16:55:04.524869815 -0500**
Change: 2015-01-19 16:55:04.524869815 -0500
  File: bla2
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: fd04h/64772d    Inode: 21          Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1709/gajacque)   Gid: ( 2015/ ccgroup)
Access: 2015-01-19 16:55:04.524869815 -0500
**Modify: 2015-01-19 16:55:04.524869815 -0500**
Change: 2015-01-19 16:55:04.524869815 -0500

I wonder if it is be possible to get a valid read of the directory entry between those 2 files.

**Comment by chanskw** [comment]
If it's going to be a problem, I do not think the problem is related to consistent region.
We would have a problem with existing operator as it relies on timestamp to determine if a tuple can be submitted.  We have not received any complaint about this operator related to timestamp or missing files.

**Comment by chanskw** [comment]
Added initial support for HDFS2FileSource and HDFS2DirectoryScan.

Pending:
* compile time checks
* docs
* Testing directory scan with file source

**Comment by chanskw** [comment]
This is now done.  Any new issues will be treated as defects.
