### ISSUE TITLE
HDFS2FileSink timeFormat

### ISSUE THREAD

**Issue by taylorsteffanj** [IBMStreams/streamsx.hdfs#46]
Using the following parameters, I see incorrect timestamps for the use of "timeFormat";

stream<rstring fileName, rstring fileSize> Output = HDFS2FileSink(Input)
{
  param
    file:"/%TIME/file%FILENUM.csv"; 
    timeFormat:"yyyy/MM/dd";
    closeOnPunct:false;
    timePerFile:3600.0;
    hdfsUser:"ISBI";
} 

The first time a timestamp is generated it is correct. For subsequent files which are received on the same date the timestamps are correct. When the date of the next file delivery has shifted, by however many days, the first file will report the timestamp (in this case a directory name) as the previous date a file landed. Subsequent files on the same date will report the correct date. The pattern when the day is shifted continues (i.e. first file has incorrect timestamp).

e.g.

Delivery Date | Timestamp Date (Directory)
01-01-2015      /2015/01/01
02-01-2015      /2015/01/01
02-01-2015      /2015/01/02
02-01-2015      /2015/01/02
04-01-2015      /2015/01/02
04-01-2015      /2015/01/04
...

(Please note: the date formats above refer to the month of January; 01 (i.e. European format)).

**Comment by conglisc** [comment]
Hi taylorsteffanj,

Can you please identify the version of the hdfs toolkit.

Thanks

**Comment by conglisc** [comment]
Hi taylorsteffanj,

Can you please double check the timestamp on the file name and the file delivery date, I am specially concerned with this line in your example.

Delivery Date | Timestamp Date (Directory)
04-01-2015 /2015/01/02

Since you are setting timePerFile to 3600 seconds, the timestamp in the file name will get refreshed in every 1 hour. Let's say the previous file is created between 11PM and 12 PM, then the HDFS2FileSink operator will continue to write content to it until the entire hour has elapsed, and a new file will be created with a new timestamp as part of its name. This will happen in the next day.

For example, if the file is created at 11:30PM on Jan 1st, then the file name should contain timestamp 2015/01/01, after 60 minutes, a new file will be created and it is created on 01-02-2015 at 0:30 AM. Its file name will contain 2015/01/02.

I am surprised to see one of your sample shows the filename still has 2015/01/02 when the file was delivered on Jan 4th, 2015. Can you please double check the timestamp of this file and the delivery date of it.

Can you please also confirm the version of the hdfs toolkit you are using.

Thanks

**Comment by taylorsteffanj** [comment]
Hello conglisc,

I can confirm the behaviour is as I previously described it.

The version of the hdfs toolkit in use is the one in v3.2.1 of InfoSphere Streams and not streamsx.hdfs. I was asked to open the ticket here by chanskw.

Thank you

**Comment by conglisc** [comment]
Hi taylorsteffanj,

I have been trying to reproduce this issue on 321, but so far I am not able to reproduce the issue. I left my test SPL app writing files to hdfs running for days, and the timestamp on the created file is matching the timestamp portion in the file or directory name.

I have also changed the rate of the data flow, i.e send tuple in every one hour or output a tuple in every 24 hours.

I wonder if you are running on a specific fix pack level of version 3.2.1?
