### ISSUE TITLE
Support append in HDFS2FileSink

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.hdfs#47]
Should allow user to append to files when writing.

**Comment by dhuszti** [comment]
I would like to use this function as well

**Comment by natashadsilva** [comment]
+1.
The missing append functionality is what led to issue #85. Because append is not supported, Gudrun tried to prevent the file from being closed prematurely by using the `closeOnPunct `parameter.  But this led to concurrent processing of punctuations and tuples, which is not handled well as documented in issue #86.
