### ISSUE TITLE
Git repository got really big in HDFS

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.hdfs#89]
I tried to clone the HDFS repository and it took us 30 min for us to clone.  After the clone is 450 M in size even though we do not have a lot files.

I investigated the problem and turns out that a *.pack file in the *.git repository is about 440M.  This is a compressed history file for Git.  I do not know what has been changed to generate this file, but we need to clean up this *.pack file and try to reduce the size of the repository.

**Comment by anouri** [comment]
The size of HDFS repository is very huge, because in the past we have uploaded a lot of sab files into repository . in samples/HDFSBluemixDemo/deploy
git clone repo
cd streamsx.hdfs
git filter-branch --index-filter 'git rm --cached --ignore-unmatch *.sab' -- --all
Rewrite 2ce13c8cbfa3f09b5a781a5f94aed11c2b721742 (198/411)rm 'samples/HDFSBluemixDemo/deploy/hdfsexample.TestDirScan.sab'
rm 'samples/HDFSBluemixDemo/deploy/hdfsexample.TestRead.sab'
rm 'samples/HDFSBluemixDemo/deploy/hdfsexample.TestWrite.sab'
Rewrite 554a472aba0313ecd38b7778b11e2dbacab14674 (199/411)rm 'samples/HDFSBluemixDemo/deploy/hdfsexample.TestDirScan.sab'
rm 'samples/HDFSBluemixDemo/deploy/hdfsexample.TestRead.sab'
rm 'samples/HDFSBluemixDemo/deploy/hdfsexample.TestWrite.sab'
Rewrite 3a181439ba9aa9ec14372f110db65d703204989d (200/411)rm 'samples/HDFSBluemixDemo/deploy/hdfsexample.TestDirScan.sab'
rm 'samples/HDFSBluemixDemo/deploy/hdfsexample.TestRead.sab'
rm 'samples/HDFSBluemixDemo/deploy/hdfsexample.TestWrite.sab'
Rewrite 2d97b56f797b6f5dd8f0e20988260a1fd768142c (201/411)rm 'samples/HDFSBluemixDemo/deploy/hdfsexample.TestDirScan.sab'
rm 'samples/HDFSBluemixDemo/deploy/hdfsexample.TestRead.sab'
rm 'samples/HDFSBluemixDemo/deploy/hdfsexample.TestWrite.sab'
Now we have to remove these large sab files from history.

**Comment by anouri** [comment]
All sab and old jar files have been removed from history of repository streamsx.hdfs.
